### ISSUE TITLE
PEPPOL AS2 conformance test

### ISSUE THREAD

**Issue by kostasathan** [holodeck-b2b/hb2b-as2#1]
Hello.

I am trying to run the PEPPOL AS2 conformance test. I have received successfully a message, but when I am trying to send the same message back, all I get is TRANSPORT_FAILURE with no other error or indication. Probably this is not the right place to address the issue, but I have run out of ideas and any help will be valuable.

Thank you.

**Comment by RenateS** [comment]
Hi Kostas,
We ran some tests following the email we received from you a couple of hours before this message and couldn't reproduce what you describe, leading us to conclude that the problem is in your configuration and not the extension.

**Comment by kostasathan** [comment]
Thank you for your answer. I never said that this might be a problem to the code, as I haven't changed anything significant. I only added some logging. Can you provide a sample pmode for AS2? I have also implemented a solution for SMP/SML communication, using your bdxr-common project.

**Comment by Mr-Rocky** [comment]
Hi,
I am also interested for sample of pmode for AS2. Can some one please provide one?

**Comment by RenateS** [comment]
Example (AS4) P-Modes are included in the core Holodeck B2B download, full instructions for configuring these for AS2 are in the Readme.md of the AS2 extension.
