### ISSUE TITLE
AS2 MepBinding configuration

### ISSUE THREAD

**Issue by kovacsgergelymusic** [holodeck-b2b/hb2b-as2#12]
Hi!

I'm trying to set up a HolodeckB2B instance to send AS2 messages. From the readme:

To indicate that a P-Mode configures an AS2 message exchange the MEP Binding parameter must be set 
http://holodeck-b2b.org/pmode/mepBinding/as2.

The link unfortonately gives me HTTP 404. I set my MEP and MEP Binding like this:

    <mep>http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/oneWay</mep>
    <mepBinding>http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/push</mepBinding>

This way however, Holodeck send my messages using AS4. How should I set up my P-mode, to use AS2?

(the as2 extension, to my best knowledge is installed)

Thanks,
Gergely

Edit:
Realized that the url is not some additional info about setting the MEP, but that should be the actual value of the setting. It works now!

**Comment by RenateS** [comment]
Hi Gergely,
Happy to see that you got it working!
Although it looks the same as a URL the string is a URI, i.e. an _identifier_ giving the schema its name.
