### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by ign404** [holodeck-b2b/hb2b-as2#6]
Failed to execute goal on project hb2b-as2: Could not resolve dependencies for project org.holodeckb2b:hb2b-as2:jar:1.1.1: The following artifacts could not be resolved: org.holodeckb2b:holodeckb2b-core:jar:4.1.1, org.holodeckb2b:holodeckb2b-security:jar:4.1.1: Could not find artifact org.holodeckb2b:holodeckb2b-core:jar:4.1.1 in central (https://repo.maven.apache.org/maven2)

**Comment by sfieten** [comment]
Hi,
the Holodeck B2B artifacts indeed are not available on a central Maven repository, so you will need to build the required artifacts and install them in your local repository. 
Therefore you will indeed experience a build error when trying to build this project without having built the main Holodeck B2B project already.
